### ISSUE TITLE
Możliwość zapisywania informacji z wyników wyszukiwania 

### ISSUE THREAD

**Issue by dawidson** [Rzezimioszek/eKW-pobieracz#1]
Przydałaby się możliwość zapisywania jedynie informacji z wyników wyszukiwania, bez konieczności wchodzenia w przeglądanie treści KW (przyspieszyłoby to pewnie znacząco masowe pobieranie danych). 

![obraz](https://github.com/Rzezimioszek/eKW-pobieracz/assets/35061534/d021c867-b35a-4617-9c4e-387097c615b5)

**Comment by Rzezimioszek** [comment]
Czy mogłoby być to pliku json w takiej formie:

 {"Numer": "xx1x/00000000/0", "Typ": "NIERUCHOMOŚĆ GRUNTOWA", "Oznaczenie": "xx WYDZIAŁ KSIĄG WIECZYSTYCH xxx", "Zapis": "20xx-08-26", "Zamknięcie": "---", "Położenie": "xxx, xxx, xxx, xxx", "Właściciel": ["xxx", "yyy", "zzz"]},

, gdzie każda księga miałaby osobny plik json.

Czy lepszą opcją według Cb będzie zapis do txt, a jeśli tak to też w formie zrzutu słownika czy może innej?
Czy opcja zapisu danych z wyszukiwania ksiąg do jednego pliku byłaby przydatna?
Czy właściciele lepiej, aby byli jak wyżej w formie listy czy może każdy właściciel był powielonym wierszem?

**Comment by dawidson** [comment]
Tak myślałem że najlepiej byłoby zapisywać wszystkie dane do jednego CSV, ewentualnie właśnie do txt jako zrzut słownika.
Dodatkowa opcja do osobnych plików json też pewnie byłaby przydatna niektórym osobom. 
Właściciele myślę że w formie listy.

**Comment by Rzezimioszek** [comment]
W wersji 0.9 (niedługo premiera) dodałem zapis pierwszego działu do xlsx oraz json, więc powstanie relacja KW numer działki. Zapis wyszukiwania już dodałem do csv oraz json
