### ISSUE TITLE
Problem ze skalowaniem GUI

### ISSUE THREAD

**Issue by dawidson** [Rzezimioszek/eKW-pobieracz#2]
Jest problem ze skalowaniem, ucina interfejs apki i nie da się zmienić rozmiaru okna

Środowisko: Windows 10 22H2; rozdzielczość 3840x2160, skalowanie 150%

![obraz](https://github.com/Rzezimioszek/eKW-pobieracz/assets/35061534/255de21c-1219-4abd-8633-b7e19d95f0c5)

**Comment by Rzezimioszek** [comment]
Z tego co wyczytałem to częsty problem przy użyciu QT i będę to naprawiać, możliwe że narazie tymczasowo, bo UI będzie jeszcze przerabiane bardziej, natomiast spóbuje to uwzględnić w następnej aktualizaji, ale nie jest to pewnik

**Comment by Rzezimioszek** [comment]
W wersji 0.9 poajwią się dwie liniki kodu, które powiny pomóc ze skalowaniem na windowsie `QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True) #use highdpi icons`
