### ISSUE TITLE
Brakujące wymaganie - Microsoft Visual C++ Redistributable 

### ISSUE THREAD

**Issue by dawidson** [Rzezimioszek/eKW-pobieracz#3]
Do działania Selenium wymagane są obydwie wersje **Microsoft Visual C++ Redistributable** (X86 i X64)
Bez tego nie da się uruchomić Chrome i aplikacja wysypuje się.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by Rzezimioszek** [comment]
Dodałem do README
